version: '3.6'

networks:
  example:
    driver: bridge

services:
  repl:
    build:
      context: .
      dockerfile: DockerfileDev
    environment:
      - WEBSERVER_PORT=${WEBSERVER_PORT}
    networks:
      - example
    ports:
      - "17021:3000"
      - "17020:17020"
    volumes:
      - $HOME:$HOME
      - $PWD:$PWD
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /tmp:/tmp
      - .:/app/
      - ./.m2:/root/.m2/repository
    user: ${CURRENT_UID}
